version: 2
jobs:
  lint:
    name: Run Spectral
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Setup Output Directory
          command: mkdir ~/junit
      - run:
          name: "Run Spectral"
          command: npx @stoplight/spectral lint reference/*.yml -f=junit -o ~/junit/test_results.xml -v -F=warn --ruleset=.spectral.yaml
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit