extends: spectral:oas
rules:
  info-contact: off
  oas3-unused-components-schema: off
  oas2-unused-definition: off
  management-api-snake-case:
    description: Management API keys should be snakeCased.
    message:  "'{{property}}' should be snakeCased"
    type: style
    given: "$.definitions[*].properties"
    severity: error
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: snake