extends:
  - spectral:oas
  - ../.spectral.yaml

rules:
  management-api-snake-case: off
  info-contact: off

except:
  'shipping_provider.yml':
    - oas2-unused-definition
  'shipping_provider.yml#/host':
    - oas2-schema