extends: spectral:oas
rules:
  storefront-api-camel-case:
    description: Storefront API keys should be camelCased.
    message:  "{{property}}"
    type: style
    given: "$.components.schemas[*].properties"
    severity: error
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: camel
        
  