extends:
  - spectral:oas
  - ../.spectral.yaml
rules:
  management-api-snake-case: off
  info-contact: off
  oas3-unused-components-schema: off
  oas2-unused-definition: off
  oas3-storefront-camel-case:
    description: Storefront API keys should be camelCased.
    message:  "Storefront API properties should be camelCased: '{{property}}'"
    type: style
    given: "$.components.schemas[*].properties"
    severity: error
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: camel
  oas2-storefront-camel-case:
    description: Storefront API keys should be camelCased.
    message:  "Storefront API properties should be camelCased: '{{property}}'"
    type: style
    given: "$.definitions[*].properties"
    severity: error
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: camel
except:
  'carts.sf.yml':
    - invalid-ref
    - oas2-valid-definition-example
    - oas2-valid-response-schema-example
    - operation-tag-defined
    - openapi-tags
    - oas3-unused-components-schema
    - oas3-storefront-camel-case
  'checkouts.sf.yml':
    - oas2-storefront-camel-case
  'customer_login.yml':
    - oas2-unused-definition
    - oas2-storefront-camel-case
    - operation-operationId
    - operation-2xx-response
  'orders.sf.yml':
    - oas2-unused-definition
    - oas2-storefront-camel-case
    - operation-tag-defined
  'customer_login.yml#/host':
    - oas2-schema
  'current_customer.yml#/host':
    - oas2-schema
  'form_fields.sf.yml#/host':
    - oas2-schema
  'form_fields.sf.yml':
    - operation-operationId
  'current_customer.yml':
    - operation-2xx-response
  'orders.sf.yml#/host':
    - oas2-schema
  'subscriptions.sf.yml#/host':
    - oas2-schema
  'subscriptions.sf.yml':
    - operation-operationId