extends:
  - spectral:oas
  - ../.spectral.yaml
rules:
  management-api-snake-case: off
  info-contact: off
  storefront-oas3-camel-case:
    description: Storefront API keys should be camelCased.
    message:  "Storefront API properties should be camelCased: '{{property}}'"
    type: style
    given: "$.components.schemas[*].properties"
    severity: error
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: camel
  storefront-oas2-camel-case:
    description: Storefront API keys should be camelCased.
    message:  "Storefront API properties should be camelCased: '{{property}}'"
    type: style
    given: "$.definitions[*].properties"
    severity: error
    then:
      field: "@key"
      function: casing
      functionOptions:
        type: camel
except:
  'carts.sf.yml':
    - invalid-ref
    - oas2-valid-definition-example
    - oas2-valid-response-schema-example
    - operation-tag-defined
    - openapi-tags
    - oas3-unused-components-schema
  'customer_login.yml':
    - oas2-unused-definition
  'orders.sf.yml':
    - oas2-unused-definition